language: generic
sudo: required  #sudo permission required

services: # what all services are required to run this job.
 - docker

before_install: # things to do before running tests
 - docker build -t imsiddhartha/docker-react -f Dockerfile.dev .

script: # running tests.
 - docker run -e CI=true imsiddhartha/docker-react npm run test

deploy: 
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "docker-react"
 env: "DockerReact-env"
 bucket_name: "elasticbeanstalk-us-east-2-271769780482"
 bucket_path: "docker-react"
 on: 
  branch: master
 access_key_id: $access_key_id
 secret_access_key: $secret_access_key

