version: '3'

services: 
        web: 
                build: 
                        context: .
                        dockerfile: Dockerfile.dev

                ports: 
                        - "3000:3000"
                volumes: 
                        - /usr/app/react-app/node_modules
                        - .:/usr/app/react-app
                stdin_open: true
                environment:
                      - CHOKIDAR_USEPOLLING=true
        tests: 
                build: 
                        context: .
                        dockerfile: Dockerfile.dev

                volumes:
                        - /usr/app/react-app/node_modules
                        - .:/usr/app/react-app
                command: ["npm","run","test"]
                stdin_open: true
                environment:
                        - CHOKIDAR_USEPOLLING=true


